#ExceptionTest
##should_customize_exception()
###Question 1: What is the knowledge point of the test? Where is the official document to the knowledge point?
Answer: The purpose of this testing is to how to use super for exception. https://www.tutorialspoint.com/Difference-between-super-and-this-in-Java
###Question 2: Why the test failed at first?
Answer: Because of the NotImplementedException.
###Question 3: Why you corrected the test that way?
Answer: By using the super() and its respective parameter.		
###Question 4: Do you have further questions on this knowledge point?
Answer: None.

##should_customize_exception_continued()
###Question 1: What is the knowledge point of the test? Where is the official document to the knowledge point?
Answer: The purpose of this testing is to how to use super for exception. https://www.tutorialspoint.com/Difference-between-super-and-this-in-Java
###Question 2: Why the test failed at first?
Answer: Because of the NotImplementedException.
###Question 3: Why you corrected the test that way?
Answer: By using the super() and its respective parameter.		
###Question 4: Do you have further questions on this knowledge point?
Answer: None.

##should_be_careful_of_the_order_of_finally_block()
###Question 1: What is the knowledge point of the test? Where is the official document to the knowledge point?
Answer: The purpose of this testing is to meet the expected and confused results.
###Question 2: Why the test failed at first?
Answer: No value or value is wrong.
###Question 3: Why you corrected the test that way?
Answer: By setting the expectedResult to confuse(2)
###Question 4: Do you have further questions on this knowledge point?
Answer: None.

##should_be_careful_of_the_order_of_finally_block()
Answer: The purpose of this testing is to how to use Optional boolean data type. https://www.tutorialspoint.com/java8/java8_optional_class.htm
###Question 2: Why the test failed at first?
Answer: Because the expected value is either no value or wrong.
###Question 3: Why you corrected the test that way?
Answer: Using to .of Optional.of(false).		
###Question 4: Do you have further questions on this knowledge point?
Answer: None.

##should_call_closing_even_if_exception_throws()
Answer: The purpose of this testing is to define the expected value coming from the try and catch. https://www.tutorialspoint.com/java/java_exceptions.htm
###Question 2: Why the test failed at first?
Answer: Because the expected value is either no value or wrong.
###Question 3: Why you corrected the test that way?
Answer: Setting the expected value to {"ClosableWithException.close", "ClosableWithoutException.close"}.		
###Question 4: Do you have further questions on this knowledge point?
Answer: None.  
   

